USE [BSCIJCEN_PRO]
GO
/****** Object:  Table [SYSPRO].[TSCIJDP9]    Script Date: 21/04/2026 15:39:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SYSPRO].[TSCIJDP9](
	[TDP9_COD_ACCION] [decimal](8, 0) NOT NULL,
	[TDP9_TIP_ACCION] [char](1) NOT NULL,
	[TDP9_NOM_TABLA] [char](15) NULL,
	[TDP9_COD_TABLA] [char](15) NULL,
	[TDP9_IDE_TABLA] [char](15) NULL,
	[TDP9_IDE_TAB_TDATO] [char](15) NULL,
	[TDP9_IDE_TAB_UNID] [char](15) NULL,
	[TDP9_LONG_MAX] [decimal](4, 0) NULL,
	[TDP9_ORDEN] [decimal](6, 0) NULL,
	[TDP9_VALORES] [varchar](200) NULL,
	[TDP9_DEFAULT] [varchar](200) NULL,
	[TDP9_TEX_ACCION] [varchar](200) NULL,
	[TDP9_DES_ACCION_C] [varchar](200) NOT NULL,
	[TDP9_DES_ACCION_E] [varchar](200) NOT NULL
) ON [BSCIJCEN_DATA]
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(100 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(50 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'0', N'', N'Introduzca el código asociado a la inspección municipal (opcional)', N'Introduzca el código asociado a la inspección municipal (opcional)_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(1 AS Decimal(8, 0)), N'C', N'TSCIJEST       ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'Seleccione Establecimiento de la lista', N'Seleccione Establecimiento de la lista_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(18 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(S)Suspensión Cautelar de Actividad,(I)Inmovilización;Suspensión Caut,Inmovilización', N'S', N'', N'Seleccione tipo de Medida Cautelar', N'Seleccione tipo de Medida Cautelar_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(3 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'2              ', N'               ', CAST(4 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'1', N'', N'Introduzca una Cantidad', N'Introduzca una Cantidad_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(15 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(100 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Introduzca la dirección de correo electrónico', N'Introduzca la dirección de correo electrónico_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(5 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(1 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(S)Si,(N)No;Bai,Ez', N'S', N'', N'¿Si, No?', N'¿Bai, Ez?')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(11 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'2              ', N'               ', CAST(9 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Introduzca el Teléfono', N'Introduzca el Teléfono_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(9 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(500 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Introduzca la Dirección', N'Introduzca la Dirección_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(17 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(LA)Licencia Apertura,(LC)Licencia Actividad,(LO)Licencia Obra,(P)Programa Especial;Irekitze baimena,Jarduera baimena,Obra baimena,Egitarau berezia', N'LA', N'', N'Seleccione el Objetivo', N'Seleccione el Objetivo_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(29 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/102/1>-15', N'', N'Autorización Sanitaria, Aviso 1', N'Autorización Sanitaria, Aviso 1_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(10 AS Decimal(8, 0)), N'D', NULL, NULL, NULL, N'1              ', NULL, CAST(1000 AS Decimal(4, 0)), NULL, NULL, NULL, NULL, N'Introduzca Observaciones', N'Introduzca Observaciones_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(7 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(F)Favorable,(D)Desfavorable;Favorable_E,Desfavorable_E', N'', N'', N'Resultado de la Inspección', N'Resultado de la Inspección_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(2 AS Decimal(8, 0)), N'C', N'TSCIJTAB       ', NULL, N'301            ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'Seleccionar Inspector', N'Seleccionar Inspector_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(6 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(1)ASF,(2)RSI Insc. Ini.,(3)RSI Convalid.,(4)RSI Amp. Act.;ASF,RSI Insc. Ini.,RSI Convalid.,RSI Amp. Act.', N'', N'', N'Seleccione tipo de Autorización', N'Seleccione tipo de Autorización_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(16 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(2 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(RS)Riesgo Sanitario,(AS)Autorización Sanitaria;Osasun Arriskua,Osasun Baimena', N'RS', N'', N'Seleccione el Objetivo', N'Seleccione el Objetivo_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(4 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'2              ', N'               ', CAST(5 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'00000', N'', N'Introduzca el número de registro', N'Introduzca el número de registro_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(8 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(100 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Introduzca el Nombre', N'Introduzca el Nombre_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(19 AS Decimal(8, 0)), N'X', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Seleccione el Fichero a Adjuntar', N'Seleccione el Fichero a Adjuntar_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(89 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_MedCaut_7.rtf', N'', N'Medidas Cautelares 7', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(90 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(DR)1ª Declaración Responsable,(S)Seguimiento;E,E', N'', N'', N'Seleccione el objetivo', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(91 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(FS)Favorable superior,(FB)Favorable nivel básico;E,E', N'', N'', N'Seleccionar resultado', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(20 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(R)Registro Municipal,(C)Correo Ordinario,(F)Fax,(M)Correo Electrónico,(P)Personado en el área de Salud y Consumo;Registro Munici,Correo Ordinari,Fax,Correo Electrón,Personado en el', N'', N'', N'Vía de Entrada de la Notificación', N'Vía de Entrada de la Notificación_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(21 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(14 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<ccc/aaaa/nnnnn>', N'', N'Código de Alerta (ccc/aaaa/nnnnn)', N'Código de Alerta (ccc/aaaa/nnnnn)_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(22 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(500 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Introduzca la Descripción', N'Introduzca la Descripción_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(23 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<fechahoy>', N'', N'Seleccione la Fecha', N'Seleccione la Fecha_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(37 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/4050601/1>-30', N'', N'Insp. Estab. Alimentarios, Aviso 4', N'Insp. Estab. Alimentarios, Aviso 4_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(36 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/40403/1>-30', N'', N'Insp. Estab. Alimentarios, Aviso 3', N'Insp. Estab. Alimentarios, Aviso 3_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(27 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<10/70903/1>-10', N'', N'Auditoria, Aviso 4', N'Auditoria, Aviso 4_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(35 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/401/1>-30', N'', N'Insp. Estab. Alimentarios, Aviso 2', N'Insp. Estab. Alimentarios, Aviso 2_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(34 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/301/1>-30', N'', N'Insp. Estab. Alimentarios, Aviso 1', N'Insp. Estab. Alimentarios, Aviso 1_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(32 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/40403/1>-30', N'', N'Autorización Sanitaria, Aviso 4', N'Autorización Sanitaria, Aviso 4_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(33 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/503/1>+1825', N'', N'Autorización Sanitaria, Aviso 5', N'Autorización Sanitaria, Aviso 5_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(28 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<10/70907/1>-30', N'', N'Auditoria, Aviso 5', N'Auditoria, Aviso 5_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(30 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/301/1>-30', N'', N'Autorización Sanitaria, Aviso 2', N'Autorización Sanitaria, Aviso 2_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(26 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<10/70801/1>-30', N'', N'Auditoria, Aviso 3', N'Auditoria, Aviso 3_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(31 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/401/1>-30', N'', N'Autorización Sanitaria, Aviso 3', N'Autorización Sanitaria, Aviso 3_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(25 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<10/703/1>-10', N'', N'Auditoria, Aviso 2', N'Auditoria, Aviso 2_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(24 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<10/601/1>-30', N'', N'Auditoria, Aviso 1', N'Auditoria, Aviso 1_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(71 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_MedCaut_6.rtf', N'', N'Medidas Cautelares Anexo 6', N'Medidas Cautelares Anexo 6')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(92 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<10/701/1>-30', N'', N'Auditoria,Aviso 2bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(72 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Sanciones_7.rtf', N'', N'Sanciones Anexo 7', N'Sanciones Anexo 7')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(70 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Denuncias_3.rtf', N'', N'Denuncias Anexo 3', N'Denuncias Anexo 3')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(38 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/102/1>+15', N'', N'Autorización Sanitaria Aviso 1 bis', N'Autorización Sanitaria Aviso 1 bis (E)')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(73 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/301/1>-15', N'', N'Insp. estab. alimentarios.Aviso 1 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(74 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/401/1>-15', N'', N'Insp. Estab. Alimentarios,Aviso 2 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(75 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/40403/1>-15', N'', N'Insp. Estab. Alimentarios, Aviso 3 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(76 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<2/4050601/1>-15', N'', N'Insp. Estab. Alimentarios, Aviso 4 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(77 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<3/40902/1>-15', N'', N'Insp. estab. aliment. por vigilancia y programas especiales, Aviso 1 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(78 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<3/4090503/1>-15', N'', N'Ins. Est. Alim.por vigilancia y programas especiales, Aviso 2 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(52 AS Decimal(8, 0)), N'Q', N'6              ', N'21             ', N'22             ', N'1              ', N'               ', CAST(14 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Seleccione Código de Alerta', N'Seleccione Código de Alerta_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(79 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/301/1>-15', N'', N'Autorización Sanitaria, Aviso 2 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(80 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/401/1>-15', N'', N'Autorización Sanitaria, Aviso 3 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(55 AS Decimal(8, 0)), N'Z', N'               ', N'52             ', N'21             ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Consulta de Movimientos Relacionados', N'Consulta de Movimientos Relacionados_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(99 AS Decimal(8, 0)), N'P', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Rellenar datos del Protocolo', N'Rellenar datos del Protocolo_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(81 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/40403/1>-15', N'', N'Autorización Sanitaria, Aviso 4 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(50 AS Decimal(8, 0)), N'I', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'', N'', N'Realice la acción indicada', N'Realice la acción indicada_E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(82 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/501/1>-15', N'', N'Autorización Sanitaria, Aviso 6 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(83 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/504/1>+1825', N'', N'Autorización Sanitaria, Aviso 5 bis', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(84 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Brotes_2.rtf', N'', N'Investigación Brotes T.I.A., anexo 2', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(85 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'10             ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<9/3/1>+30', N'', N'Sanciones, Aviso 1', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(86 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<9/801/1>+30', N'', N'Sanciones Aviso 2', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(87 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<1/201/1>30', N'', N'Autorización Sanitaria, fecha prevista inspección', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(88 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'Plant_MedCaut_7.rtf', N'', N'', N'Medidas Cautelares 7', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(61 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Alertas_2.rtf', N'', N'Alertas Anexo 2', N'Alertas Anexo 2')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(60 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Alertas_1.rtf', N'', N'Alertas Anexo 1', N'Alertas Anexo 1')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(62 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Alertas_3.rtf', N'', N'Alertas Anexo 3', N'Alertas Anexo 3')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(63 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Auditoria_1.rtf', N'', N'Auditoria Anexo 1', N'Auditoria Anexo 1')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(64 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Auditoria_4.rtf', N'', N'Auditoria Anexo 4', N'Auditoria Anexo 4')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(65 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_AutSan_5.rtf', N'', N'Autorización Sanitaria Anexo 5', N'Autorización Sanitaria Anexo 5')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(66 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_AutSan_GV.rtf', N'', N'Autorización Sanitaria Anexo GV', N'Autorización Sanitaria Anexo GV')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(67 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Brotes_1.rtf', N'', N'Brotes Anexo 1', N'Brotes Anexo 1')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(68 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Denuncias_1.rtf', N'', N'Denuncias Anexo 1', N'Denuncias Anexo 1')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(69 AS Decimal(8, 0)), N'Y', N'               ', N'               ', N'               ', N'               ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'Plant_Denuncias_2.rtf', N'', N'Denuncias Anexo 2', N'Denuncias Anexo 2')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(56 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(3 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(ASF)Autorización Sanitaria,(INS)Insp. normalizada,(IVP)Vigilancia ,(DEN)Denuncias,(TIA)Brotes,(ALE)Alertas;E,E,E,E,E,E,', N'', N'', N'Seleccionar proceso de orígen', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(57 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'1              ', N'               ', CAST(0 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'(LA)L Apertura,(LC)L Actividad,(LO)L Obra,(P)Programa Especial,(V)Vigilancia;E,E,E,E,E', N'', N'', N'Seleccione el objetivo', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(58 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<3/40902/1>-30', N'', N'Inspección estab. alim. por vigilancia y programas espaciales,Aviso 1', N'E')
GO
INSERT [SYSPRO].[TSCIJDP9] ([TDP9_COD_ACCION], [TDP9_TIP_ACCION], [TDP9_NOM_TABLA], [TDP9_COD_TABLA], [TDP9_IDE_TABLA], [TDP9_IDE_TAB_TDATO], [TDP9_IDE_TAB_UNID], [TDP9_LONG_MAX], [TDP9_ORDEN], [TDP9_VALORES], [TDP9_DEFAULT], [TDP9_TEX_ACCION], [TDP9_DES_ACCION_C], [TDP9_DES_ACCION_E]) VALUES (CAST(59 AS Decimal(8, 0)), N'D', N'               ', N'               ', N'               ', N'3              ', N'               ', CAST(10 AS Decimal(4, 0)), CAST(0 AS Decimal(6, 0)), N'', N'<3/4090503/1>-30', N'', N'Insp. Estab. Alim.por vigilancia y programas especiales, Aviso 2', N'E')
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_NOM_TABLA]  DEFAULT (NULL) FOR [TDP9_NOM_TABLA]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_COD_TABLA]  DEFAULT (NULL) FOR [TDP9_COD_TABLA]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_IDE_TABLA]  DEFAULT (NULL) FOR [TDP9_IDE_TABLA]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_IDE_TAB_TDATO]  DEFAULT (NULL) FOR [TDP9_IDE_TAB_TDATO]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_IDE_TAB_UNID]  DEFAULT (NULL) FOR [TDP9_IDE_TAB_UNID]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_LONG_MAX]  DEFAULT (NULL) FOR [TDP9_LONG_MAX]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_ORDEN]  DEFAULT (NULL) FOR [TDP9_ORDEN]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_VALORES]  DEFAULT (NULL) FOR [TDP9_VALORES]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_DEFAULT]  DEFAULT (NULL) FOR [TDP9_DEFAULT]
GO
ALTER TABLE [SYSPRO].[TSCIJDP9] ADD  CONSTRAINT [DF_TSCIJDP9_TDP9_TEX_ACCION]  DEFAULT (NULL) FOR [TDP9_TEX_ACCION]
GO
