USE [BSCIJCEN_PRO]
GO
/****** Object:  Table [SYSPRO].[TSCIJPR1]    Script Date: 21/04/2026 15:35:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SYSPRO].[TSCIJPR1](
	[TPR1_COD_TIPO] [decimal](5, 0) NULL,
	[TPR1_DES_TIPO] [varchar](100) NOT NULL,
	[TPR1_TEX_TIPO] [varchar](4000) NOT NULL,
	[TPR1_DES_TIPO_E] [varchar](100) NOT NULL,
	[TPR1_TEX_TIPO_E] [varchar](4000) NOT NULL,
	[TPR1_FEC_BAJA] [date] NOT NULL
) ON [BSCIJCEN_DATA]
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(1070 AS Decimal(5, 0)), N'Comedores colectivos: Establecimientos de hostelería grupo II.', N'Establecer%20las%20condiciones%20y%20requisitos%20espec%EDficos%20que%20deben%20cumplir%20los%20establecimientos%20de%20hosteler%EDa%20del%20grupo%20II%2C%20de%20acuerdo%20a%20su%20riesgo%20sanitario.%0D%0ALos%20establecimientos%20de%20hosteler%EDa%20del%20grupo%20II%20son%20aquellos%20comedores%20colectivos%20que%20elaboran%20y%20sirven%20men%FAs%20o%20comidas%20completas%2C%20muy%20variadas%2C%20con%20ingredientes%20de%20diversa%20naturaleza%20y%20origen%2C%20que%20sufren%20preparaciones%20tambi%E9n%20variadas%2C%20y%20con%20servicio%20de%20los%20mismos%20en%20un%20comedor%20o%20zona%20habilitada%20al%20efecto.%20Se%20incluyen%20establecimientos%20de%20hosteler%EDa%20con%20men%FA%20y/o%20carta%2C%20y%20asimilables.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(1 AS Decimal(5, 0)), N'Mataderos grandes especies.', N'Establecer las condiciones y requisitos específicos que deben cumplir los mataderos como establecimientos para la matanza de los animales (vacuno, equino, porcino, ovino, caprino) destinados al consumo humano en todas sus fases de producción, desde la llegada de los animales al matadero hasta la expedición de las carnes, exceptuando los mataderos de producción limitada.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(2 AS Decimal(5, 0)), N'Mataderos de aves.', N'Establecer las condiciones y requisitos específicos que deben cumplir los mataderos de aves, como establecimientos para la matanza de aves para consumo humano, en todas sus fases de producción, desde la llegada de os animales al matadero hasta la expedición de las carnes, exceptuando los mataderos de aves de producción limitada.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(3 AS Decimal(5, 0)), N'Mataderos de conejos.', N'Establecer las condiciones y requisitos específicos que deben cumplir los mataderos de conejos, como establecimientos para la matanza de conejos para consumo humano, en todas sus fases de producción, desde la llegada de los animales al matadero hasta la expedición de las carnes, exceptuando los mataderos de conejos de producción limitada.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(4 AS Decimal(5, 0)), N'Sala de despiece de carnes.', N'Establecer las condiciones y requisitos específicos que deben cumplir las salas de despiece de carnes dedicadas a la obtención y comercialización de porciones más peque¦as que las canales, las medias canales y las medias canales despiezadas en un máximo de tres piezas o los cuartos, al deshuese de las mismas, su envasado o no y a la comercialización de despojos (enteros envasados o no) o fileteados. Todas ellas procedentes de animales domésticos de las especies bovina, porcina, ovina, caprina y los solípedos domésticos.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(5 AS Decimal(5, 0)), N'Almacén frigorífico de carnes.', N'Establecer las condiciones y requisitos específicos que deben cumplir los almacenes frigoríficos de carnes y despojos ,embalados o no, procedentes de los animales domésticos de las especies bovina, porcina, ovina, caprina y los solípedos domésticos que no se someten a ninguna manipulación salvo aquella necesarias para el almacenamiento de las mismas.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(6 AS Decimal(5, 0)), N'Salas de despiece de poca capacidad.', N'Salas de despiece de poca capacidad.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(8 AS Decimal(5, 0)), N'Almacén frigorífico de carne de aves de corral.', N'Establecer las condiciones y requisitos específicos que deben cumplir lao almacenes frigoríficos de carnes y despojos de aves, procedentes de las aves domesticas de las siguientes especies: gallinas, patos, ocas, pavos y pintadas, que no se someten a ninguna manipulación salvo aquella necesarias para el almacenamiento de las mismas.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(9 AS Decimal(5, 0)), N'Sala de despiece de carne de aves de corral.', N'Establecer%20las%20condiciones%20y%20requisitos%20espec%EDficos%20que%20deben%20cumplir%20las%20salas%20de%20despiece%20de%20carne%20fresca%20de%20aves%20de%20corral%20dedicadas%20a%20la%20obtenci%F3n%20y%20comercializaci%F3n%20de%20partes%20de%20canales%20y%20sus%20despojos%20o%20carnes%20deshuesadas%20y%20su%20envasado%20y/o%20embalado.%20Todas%20ellas%20procedentes%20de%20aves%20dom%E9sticas%20de%20las%20siguientes%20especies%3A%20gallinas%2C%20patos%2C%20ocas%2C%20pavos%20y%20pintadas.%20', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(10 AS Decimal(5, 0)), N'Almacén frigorífico de carne de conejo y aves de caza de granja.', N'Establecer las condiciones y requisitos específicos que deben cumplir los almacenes frigoríficos de carne fresca de conejo doméstico y aves de caza de granja, que no se someten a ninguna manipulación salvo aquella necesarias para el almacenamiento de las mismas.
Entendiendo por aves de caza de granja aquellas aves no domésticas (distintas de gallinas, pavos, patos, pintadas y gansos), incluidas codornices, palomas, faisanes, perdices y aves corredoras, pero criadas como aves domésticas.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(11 AS Decimal(5, 0)), N'Sala de despiece de carne de conejo y aves de caza de granja.', N'Establecer las condiciones y requisitos específicos que deben cumplir las salas de despiece de carne fresca de conejo doméstico y aves de caza de granja dedicadas a la obtención y comercialización de partes de canales y sus despojos o carnes deshuesadas y a su envasado y/o embalado. 
Entendiendo por aves de caza de granja aquellas aves no domésticas (distintas de gallinas, pavos, patos, pintadas y gansos), incluidas codornices, palomas, faisanes, perdices y aves corredoras, pero criadas como aves domésticas.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(12 AS Decimal(5, 0)), N'Productos cárnicos.', N'Establecer las condiciones y requisitos específicos que deben reunir los establecimientos dedicados a la producción, troceado en su caso, envasado, almacenamiento y comercialización de:
Los productos cárnicos, siendo estos los elaborados a partir de carne y que sufre un tratamiento tecnológico que provoca la desaparición de las características de la carne fresca en la parte central de la superficie del corte. Quedando excluidos como tales las carnes sometidas a tratamiento de frío (refrigeración y/o congelación), las carnes picadas, las carnes en trozos de menos de 100 gr. y  los preparados de carne. En este sentido se consideran productos cárnicos a : los embutidos escaldados, cocidos, curados, secados, ahumados/ adobados, a las salazones cárnicas, a los adobados previa salazón, a las conservas (pasteurizadas o estereilizadas).
Quedan exceptuados los establecimientos de venta al por menor o locales contiguos a los puntos de venta.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(13 AS Decimal(5, 0)), N'Productos cárnicos de establecimientos con estructura no industrial.', N'Productos cárnicos de establecimientos con estructura no industrial.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(14 AS Decimal(5, 0)), N'Carne picada y preparados de carne.', N'
Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos (excepto los establecimientos de venta al por menor o locales adyacentes a los mismos) dedicados a la producción y comercialización de:
Carne picada, carne que ha sido sometida a una operación de picado en fragmentos o al paso por una máquina picadura continua. Si se destina a intercambios intracomunitarios, solamente se podrá obtener de las carnes provenientes de las especies bovina, porcina, ovina y caprina. Si se destina al mercado nacional, se podrá obtener de las carnes provenientes de las especies bovina, porcina, ovina, caprina, solípedos domésticos, gallinas, pavos, patos, pintadas, ocas, conejos, caza de granja y caza silvestre.
Preparados de carne, productos elaborados con carnes aptas para el consumo humano a las que se haya a¦adido productos alimenticios, condimentos o aditivos y/o que hayan sido sometidas a un tratamiento insuficiente para modificar la estructura celular de la carne en la parte central  de la superficie de corte y hacer desaparecer así las características de la carne fresca. Además de otros, se consideran preparados de carne las denominaciones de: crudos-adobados, salchichas crudas, butifarras frescas, longanizas frescas, chorizos frescos, hamburguesas y albóndigas. Si se destina a intercambios intracomunitarios, solamente se podrá obtener de las carnes provenientes de las especies bovina, porcina, ovina y caprina. Si se destina al mercado nacional, se podrá obtener de las carnes provenientes de las especies bovina, porcina, ovina, caprina, solípedos domésticos, gallinas, pavos, patos, pintadas, ocas, conejos, caza de granja y caza silvestre.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(15 AS Decimal(5, 0)), N'Preparados de carne de estructura no industrial.', N'Preparados de carne de estructura no industrial.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(16 AS Decimal(5, 0)), N'Carnicería-Salchichería', N'Establecer las condiciones y requisitos específicos que deben cumplir las carnicerías-salchicherías, entendiendo por éstas como aquellos establecimientos que:
1º.-Están formados por un local o conjunto de locales bajo titularidad única, que según su ubicación pueden:
a) Estar independientes
b) Estar integrados en una unidad comercial de mayor entidad, compartiendo servicios-vestuarios y elementos comunes de la unidad con otros establecimientos.
c) Ser una sección de un establecimiento polivalente, debiendo estar claramente separada e identificada del resto de secciones y podrán compartir los servicios-vestuarios y elementos comunes de dicho establecimiento polivalente.
2º.-Se dedican a la manipulación, preparación y presentación de carnes y despojos frescos (refrigerados o congelados) con o sin hueso en sus diferentes modalidades: fileteado, troceado, picado, mechado y otras análogas a estas. Además a la elaboración de: preparados de carne (frescos y crudos adobados) y/o embutidos de sangre (morcillas) y aquellos otros considerados tradicionales y que las autoridades sanitarias autoricen expresamente una vez valoradas las peticiones que las asociaciones de carniceros presenten. En caso de adoptar la aprobación de algún producto tradicional, se incluiría en el listado de productos a elaborar. También puede realizar el salazonado de tocino.
3º.-Las carnes y despojos que comercializan deben ser aptas para consumo humano, obtenidas en establecimientos autorizados y provenientes de animales domésticos (especies bovina, porcina, ovina, caprina, solípedos, gallinas, pavos, pintadas, patos, ocas y conejos) mamíferos terrestres y aves silvestres reproducidos, criados y sacrificados en cautividad, caza silvestre y reses de lidia de espectáculos taurinos. Según esta definición, y a efectos de clarificar las actividades, puede suceder que en mercados y galerías comerciales existan establecimientos que su actividad principal y casi única sea la de comercializar carnes de aves y elaborar preparados cárnicos frescos y crudos adobados con carnes de ave. En este caso su denominación sería la de POLLERIA-SALCHICHERIA, pero a efectos de requisitos higiénicos-sanitarios serían los recogidos en la presente IT.
4º.-Los productos que elaboran estos establecimientos solo pueden ser comercializadas en sus propias dependencias de venta al público y en las sucursales.
Entendemos por sucursales a las carnicerías que incorporan a los productos que comercializan, aquellos productos elaborados en otro considerado central, de la misma titularidad que ellos y localizados en la misma Comarca de Salud Pública donde se encuentra este establecimiento central. Asi tenemos según Territorio Histórico:
.- En Bizkaia: Interior, Gernika Lea-Artibay, Uribe Kosta, Margen Izquierda-Encartaciones y Bilbao.
.- En Guipúzcoa: Urola, Deba, Tolosa-Goierri, Bidasoa y Donostia.
.- En Araba: Araba Rural, Aiara y Rioja Alavesa.
5º.-Con excepción de los preparados cárnicos frescos y las carnes picadas, estos establecimientos solamente podrán suministrar a los establecimientos de comidas preparadas no sujetos a inscripción en el R.G.S.A. ubicados dentro del ámbito territorial de la Comarca de Salud Pública en la que se encuentra ubicado dicho establecimiento.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(17 AS Decimal(5, 0)), N'Lonjas pesqueras y mercados al por mayor.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos donde se realiza la exposición y primera venta al por mayor de productos de la pesca( lonja pesquera) o los centros de concentración de productos de la pesca, en los que únicamente se efectúe la exposición y venta al por mayor (mercado al por mayor).', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(18 AS Decimal(5, 0)), N'Buques pesqueros.', N'Buques pesqueros.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(19 AS Decimal(5, 0)), N'Transformación de productos de la pesca.', N'Establecer las condiciones y requisitos específicos que, de manera general, deben cumplir los establecimientos en tierra en que se preparen, transformen, refrigeren, congelen, envasen y/o embalen, o depositen productos pesqueros. No se consideran establecimientos los mercados de subastas ni los mercados al por mayor en los que únicamente se efectúen la exposición y la venta al por mayor, ni las depuradoras de moluscos y cetáreas, ni los buques, ni los establecimientos dedicados únicamente al almacenamiento frigorífico, ni los comercios al por menor de productos pesqueros.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(20 AS Decimal(5, 0)), N'Centros de expedición y de depuración de molusculos bivalvos.', N'Establecer los requisitos que deben cumplir los centros de expedición y de depuración de moluscos bivalvos ( moluscos lamelibranquios que se alimentan por filtración ), entendiéndose por CENTRO DE EXPEDICIÓN a toda instalación terrestre o flotante, homologada, en la que se reciben, acondicionan (los moluscos que no precisan depuración se almacenan en tanques con agua de mar limpia), lavan, limpian, calibran y envasan moluscos bivalvos aptos para consumo humano y entendiéndose por CENTRO DE DEPURACIÓN, los establecimientos homologados que disponen de estanques alimentados por agua de mar limpia de manera natural o depurada mediante un tratamiento adecuado, en los que se mantienen los moluscos bivalvos vivos durante el tiempo necesario para que puedan eliminar la contaminación de origen microbiano, con el fin de convertirlos en aptos para el consumo humano.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(21 AS Decimal(5, 0)), N'Pescaderías.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos dedicados a la venta al por menor de productos de la pesca destinados al consumo humano.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(22 AS Decimal(5, 0)), N'Almacén de pesca.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos dedicados al almacenamiento de productos de la pesca bien refrigerados o bien congelados y/o aquellos que se dedican a la congelación de productos pesqueros. Asimismo, se incluyen aquellos establecimientos que realizan únicamente el reenvasado de productos pesqueros.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(23 AS Decimal(5, 0)), N'Centro de cetárea.', N'Establecer los requisitos que deben cumplir los establecimientos dedicados a mantener , envasar y distribuir, los crustáceos vivos, durante un periodo de tiempo bajo condiciones controladas en agua de mar limpia, en tanques, balsas, o parques flotantes. ', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(24 AS Decimal(5, 0)), N'Buques congelados.', N'Buques congelados.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(25 AS Decimal(5, 0)), N'Clasificación y envasado de huevos.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los centros de embalaje (centros de clasificación) de huevos.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(26 AS Decimal(5, 0)), N'Elaboración de ovoproductos.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos elaboradores de ovoproductos, (productos obtenidos del huevo, sus componentes o sus mezclas, sin cáscara ni membranas, completados o no con productos alimenticios o aditivos y en estado líquido, concentrado, desecado, congelado o ultra congelado), desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(27 AS Decimal(5, 0)), N'Establecimientos de elaboración de caramelos, chicles, confites y golosinas.', N'Establecer las condiciones y requisitos que deben cumplir de forma específica los establecimientos dedicados a la actividad de elaboración y/o envasado de caramelos, chicles, confites y golosinas.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(28 AS Decimal(5, 0)), N'Tubérculos (transformación y envasado de patata fresca refrigerada).', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de transformación / procesado de patata fresca: Pelado, troceado, desfeculado, ba¦o de tratamiento (salmuera y antioxidante), escurrido, envasado, embalado y conservación frigorífica.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(29 AS Decimal(5, 0)), N'Establecimientos elaboradores de pan y panes especiales.', N'Establecer las condiciones y requisitos específicos que deben cumplir los elaboradores y fabricantes de productos de panadería.
Se consideran elaboradores y fabricantes de productos de panadería, aquellos establecimientos o industrias que dedican su actividad a la elaboración de pan y panes especiales.
Se define como pan, el producto resultante de la cocción de una masa obtenida por la mezcla de harina de trigo y agua potable, con o sin adición de sal comestible, fermentada por especies de microorganismos propios de la fermentación panadería. Se considera pan común el definido anteriormente, al que solamente se le pueden a¦adir los coadyuvantes tecnológicos y aditivos autorizados para este tipo de pan.
Se considera pan especial el no incluido en la definición anterior y que reúna alguna de las condiciones siguientes: 
Que se haya incorporado cualquier aditivo y/o coadyuvante tecnológico autorizado para panes especiales.
Que se haya utilizado como materia harina enriquecida.
Que se haya a¦adido cualquier ingrediente que eleve su valor nutritivo.
Que no lleve microorganismos propios de la fermentación, voluntariamente a¦adidos.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(30 AS Decimal(5, 0)), N'Pastas alimenticias.', N'Pastas alimenticias.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(31 AS Decimal(5, 0)), N'Minorista de panadería.', N'Minorista de panadería.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(32 AS Decimal(5, 0)), N'Pastelerías.', N'Establecer las condiciones y requisitos específicos que deben cumplir los obradores de pastelería.
Obradores de pastelería: son aquellos establecimientos, de carácter industrial o no, que elaboran, envasan, almacenan, distribuyen y/o importan productos de pastelería.
Los productos de pastelería son aquellos elaborados, fermentados o no, de diversa forma, tama¦o y composición, integrados fundamentalmente por harinas, féculas, azúcares, grasas comestibles y otros productos alimenticios y alimentarios como sustancias complementarias.
Los obradores de pastelería se diferenciarán en industriales o no industriales. Tendrán la consideración de industriales aquellos en los que se den estas circunstancias:
.- Comercializan sus productos por terceros, además o no de en despachos de su propiedad.
.- Tienen distribuciones amplias, incluyendo venta en sector minorista, fuera de su municipio, y   frecuentemente de productos envasados.
.- Sus volúmenes de producción son grandes.
Las condiciones de etiquetado y trazabilidad deben cumplirlas los establecimientos de tipo industrial que comercializan productos envasados y embalados (por ejemplo, ¦astas, galletas, etc.)
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(33 AS Decimal(5, 0)), N'Establecimientos envasadores de azúcar.', N'Establecer las condiciones y requisitos que deben cumplir de forma específica los establecimientos dedicados a la actividad de envasado de azúcar.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(34 AS Decimal(5, 0)), N'Establecimientos de extracción y envasado de miel.', N'Establecer las condiciones y requisitos que deben cumplir de forma específica los establecimientos dedicados a la actividad de extracción y/o envasado de miel (néctar y mielada).
Las mieles se clasifican en:
-Mieles de consumo directo
Dependiendo de su origen floral se denominará con el término miel seguido de flores, milflores, la especie unifloral o de mielada. La que proceda de mieles de flores y de mielada se denominará miel de flores y mielada.
.La miel en panales, miel en secciones y la miel con trozos de panal miel escurrida, miel centrifugada, miel prensada y miel filtrada.
-Las mieles con destino a la industria se denominarán o miel de industria.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(35 AS Decimal(5, 0)), N'Establecimientos elaboradores de turrones y mazapanes.', N'Establecer las condiciones y requisitos que deben cumplir de forma específica los establecimientos dedicados a la actividad de elaboración de turrones y mazapanes.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(36 AS Decimal(5, 0)), N'Comedores colectivos institucionales que elaboran comidas.', N'Establecer las condiciones y requisitos específicos que deben cumplir los comedores colectivos institucionales que elaboran comidas en sus instalaciones, de acuerdo a su riesgo sanitario.
Comedores institucionales: comedores colectivos que forman parte de empresas, centros o instituciones como actividad accesoria de éstos. A efectos de su autorización sanitaria de funcionamiento, se clasifican en comedores escolares, comedores de empresa, comedores de residencias, cocinas de hospitales o clínicas y otros comedores institucionales.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(37 AS Decimal(5, 0)), N'Comedores colectivos institucionales sin elaboración comidas.', N'Establecer las condiciones y requisitos específicos que deben cumplir los comedores colectivos institucionales que no elaboran comidas, de acuerdo a su riesgo sanitario.
Comedores institucionales: comedores colectivos que forman parte de empresas, centros o instituciones como actividad accesoria de éstos. A efectos de su autorización sanitaria de funcionamiento, se clasifican en comedores escolares, comedores de empresa, comedores de residencias, cocinas de hospitales o clínicas y otros comedores institucionales.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(38 AS Decimal(5, 0)), N'Elaboración de platos preparados no industriales Grupo I.', N'Establecer las condiciones y requisitos especificos que deben cumplir los establecimientos de elaboración de platos preparados no industriales, de acuerdo a su riesgo sanitario.
Los establecimientos de elaboración de platos preparados no industriales del grupo I son aquellos cuya actividad sea facilitar comidas preparadas de bajo riesgo que no se consumen en el mismo local donde se elaboran, pudiendo ser vendidas al consumidor final para su consumo fuera del establecimiento de elaboración, o suministradas al mismo en su domicilio particular.
Se incluyen en este grup las pizzerías, hamburgueserías, bacaterías, los establecimientos de elaboración y venta de pollos asados y asimilables.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(39 AS Decimal(5, 0)), N'Cocinas centrales.', N'Establecer las condiciones y requisitos específicos que deben cumplir las cocinas centrales, de acuerdo a su riesgo sanitario.
Cocina central: establecimiento que elabora comidas completas para su distribución a colectividades, entendidas éstas como entidades sociales públicas o privadas que agrupan a un conjunto de individuos con características similares (empresas, colegios, residencias, hospitales, asociaciones o similares) que demandan un servicio de comidas preparadas.
Será considerado también colectividad, el conjunto de individuos agrupados con motivo de celebraciones, banquetes y similares.
La distribución de dichas comidas podrá realizarse en caliente o en frío para su consumo directo sin tratamiento térmico adicional o tras una regeneración térmica. 
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(40 AS Decimal(5, 0)), N'Industrias de platos preparados.', N'Industrias de platos preparados.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(42 AS Decimal(5, 0)), N'Agua de bebida envasada.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos relacionados con el envasado, almacenamiento y comercialización de aguas de bebida envasadas.
Se entienden como aguas de bebida envasadas las siguientes:
Aguas minerales naturales: aquellas bacteriológicamente sanas que tengan su origen en un estrato o yacimiento subterráneo y que broten de un manantial en uno o varios puntos de alumbramiento, naturales o perforados.
Éstas pueden distinguirse claramente de las restantes aguas potables por su naturaleza caracterizada por su contenido en minerales, oligoelementos y otros componentes y en ocasiones por determinados defectos.
Aguas de manantial: son las potables de origen subterráneo que emergen espontáneamente en la superficie de la tierra o se captan mediante labores practicadas al defecto, con las características naturales de pureza que permiten su consumo.
Aguas preparadas: son las sometidas a tratamientos fisicoquímicos necesarios para su potabilización, pudiendo ser Potables Preparadas cuando procedan de manantial o captación o de Abastecimiento Público Preparadas en el supuesto de tener dicha procedencia.
Aguas de consumo público envasadas: son aquellas aguas potables de consumo público, envasadas coyunturalmente para distribución domiciliaria, con el único objeto de suplir ausencias o insuficiencias accidentales de las aguas de consumo público distribuidas por la red general.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(43 AS Decimal(5, 0)), N'Fabricación de hielo.', N'Establecer%20las%20condiciones%20y%20requisitos%20espec%EDficos%20que%20deben%20cumplir%20los%20establecimientos%20relacionados%20con%20la%20producci%F3n%20y%20comercializaci%F3n%20del%20hielo.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(44 AS Decimal(5, 0)), N'Establecimientos elaboradores de helados y mezclas envasadas para congelar.', N'Establecer las condiciones específicas a las que han de atenerse los establecimientos dedicados a la elaboración, envasado y circulación de helados y mezclas envasadas para congelar, incluyéndose  los establecimientos de producción limitada y los que elaboran para  venta en el propio establecimiento.
Los establecimientos de producción limitada son aquellos: cuya producción sea inferior a 400.000 litros de leche al a¦o.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(45 AS Decimal(5, 0)), N'Bebidas refrescantes (elaboración y envasado).', N'Establecer las condiciones y requisitos específicos que deben cumplir las industrias de elaboración y envasado de bebidas refrescantes.
Se entiende por bebida refrescante la preparada con agua potable y los ingredientes y demás productos autorizados, adicionada o no de anhídrido carbónico.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(46 AS Decimal(5, 0)), N'Bebidas alcohólicas: Vino/txakoli (elaboración y/o envasado).', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de elaboración y/o envasado de VINO / TXAKOLI.
Se entiende por vino el producto obtenido exclusivamente por la fermentación alcohólica, total o parcial, de uva fresca, estrujada o no, o de mosto de uva. Tendrá un grado alcohólico volumétrico adquirido no inferior al 8,5% así como un grado alcohólico volumétrico total no superior al 15%.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(47 AS Decimal(5, 0)), N'Bebidas alcohólicas: Sidra  natural (elaboración y envasado).', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de elaboración, embotellado y almacenamiento de sidra natural. Entendiéndose por tal, la elaborada siguiendo las prácticas tradicionales, sin adición de azúcares, que contiene gas carbónico de origen endógeno exclusivamente. Su graduación alcohólica adquirida será superior a  4%B45 grados.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(48 AS Decimal(5, 0)), N'Bebidas espirituosas (elaboración y/o envasado).', N'Establecer las condiciones y requisitos específicos que deben cumplir las industrias de elaboración y/o envasado de bebidas espirituosas, entendiendo por tal el liquido alcohólico destinado al consumo humano de características organolepticas especiales, con un grado alcohólico mínimo de 15 % vol, obtenido:
Directamente por destilación (en presencia o no de aromas) de productos naturales fermentados.
Por maceración de sustancias vegetales o adición de aromas, azucares u otros edulcorantes al alcohol etílico de origen agrícola, a un destilado de origen agrícola o a un aguardiente.
Por mezcla de una o varias bebidas espirituosas con alcohol etílico de origen agrícola, destilados, aguardientes u otras bebidas alcohólicas.
Entre ellas podemos citar: El Ron, Whisky, Cognac, Brandy, Orujo, Pacharán, Ginebra, Anís y derivados, diversos Licores y Aguardientes (de frutas, de huevo, de café, Vodka, Tequila, Pastís,?), Ponches y bebidas aperitivas, etc.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(49 AS Decimal(5, 0)), N'Bebidas alcohólicas: Cerveza (elaboración y/o envasado).', N'Establecer las condiciones y requisitos específicos que deben cumplir las industrias de elaboración y/o envasado de cerveza y malta líquida, considerada como la bebida resultante de la fermentación alcohólica, mediante levadura seleccionada, de un mosto procedente de malta de cebada, solo o mezclado con otros productos amiláceos transformables en azúcares por digestión enzimática, adicionado con lúpulo y/o sus derivados y sometido a un proceso de cocción.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(50 AS Decimal(5, 0)), N'Almacenes frigoríficos.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de almacenamiento frigorífico de alimentos y productos alimentarios.
Quedan exceptuadas aquellas actividades que pudieran realizarse en los almacenes frigoríficos y que tengan establecidas normas específicas, a través de sus Reglamentaciones Técnico Sanitarias.

', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(51 AS Decimal(5, 0)), N'Almacenes no frigoríficos.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de almacenamiento  no frigorífico de alimentos y productos alimentarios.
Quedan exceptuadas aquellas actividades que pudieran realizarse en los almacenes y que tengan establecidas normas específicas, a través de sus Reglamentaciones Técnico Sanitarias.

', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(52 AS Decimal(5, 0)), N'Establecimientos no permanentes.', N'Establecer las condiciones y requisitos específicos que se deben cumplir en el ejercicio de la actividad de venta en establecimientos no permanentes, entendiendo como tal actividad la realizada por vendedores habituales u ocasionales de un establecimiento comercial, en puestos o instalaciones desmontables, así como en vehículos. Se incluye también la venta en los quioscos como establecimiento ubicado en la vía pública de forma permanente.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(53 AS Decimal(5, 0)), N'Grasas y aceites vegetales comestibles.', N'Establecer las condiciones y requisitos específicos que deben cumplir las industrias de elaboración y/o envasado, circulación y comercio de grasas comestibles animales, vegetales y anhidras y aceites vegetales comestibles.
Grasas comestibles son los productos de origen animal, vegetal o sus mezclas, cuyos componentes principales sean glicéridos de los ácidos grasos, pudiendo tener otros componentes menores.
Grasas animales son las obtenidas, por distintos procedimientos, a partir de diversos depósitos adiposos de determinados animales en adecuado estado sanitario Manteca de cerdo, grasa de cerdo fundida, primeros jugos, sebos comestibles y otras grasas animales.
Grasas vegetales: son las obtenidas, por distintos procedimientos, de frutos o semillas sanas y limpias Manteca de coco, grasa de palmiste, manteca de palma, manteca de cacao y otras grasas vegetales.
Grasas anhidras: las constituidas por aceites y/o grasas comestibles y sus mezclas, de aspecto homogéneo y con una humedad no superior a 0,5 por 100. Estas grasas se destinan a la alimentación a través de industrias alimentarias o para uso doméstico en preparaciones culinarias.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(54 AS Decimal(5, 0)), N'Condimentos y especias.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de elaboración de condimentos y especias, desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(55 AS Decimal(5, 0)), N'Alimentos estimulantes.', N'Alimentos estimulantes.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(56 AS Decimal(5, 0)), N'Elaboración de aditivos y aromas.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de elaboración de aditivos y aromas, desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(57 AS Decimal(5, 0)), N'Sal y salmueras comestibles.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de elaboración de sal y salmueras comestibles, desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(58 AS Decimal(5, 0)), N'Establecimientos de hortalizas, verduras, hongos, fruta fresca congelada y deshidratada.', N'Establecer los requisitos técnico-sanitarios que tienen que cumplir los establecimientos dedicados a la actividad de almacenamiento y procesado de hortalizas, verduras, hongos, frutas frescas; elaboración de frutas y hortalizas secas, desecadas y deshidratadas. ', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(59 AS Decimal(5, 0)), N'Establecimientos de elaboración y/o envasado de vinagre.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de elaboración y envasado de vinagre, desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(60 AS Decimal(5, 0)), N'Elaboración de cacao, chocolate, sus derivados y sucedáneos.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de elaboración de cacao, chocolate, sus derivados y sucedáneos, desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(61 AS Decimal(5, 0)), N'Elaboración de café, sucedáneos del café, achicoria, té e infusiones.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos de elaboración de café, sucedáneos del café, achicoria, té e infusiones, desde la recepción de materias primas hasta el etiquetado y distribución del producto final.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(62 AS Decimal(5, 0)), N'Detergentes y desinfectantes.', N'Detergentes y desinfectantes.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(63 AS Decimal(5, 0)), N'Materiales en contacto con alimentos.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos que se dedican a la fabricación, transformación, y comercialización (importación de fuera del ámbito de la CE, almacenamiento, envasado y distribución) de materiales, objetos y sus partes que estén destinados a entrar en contacto o se pongan en contacto con productos alimenticios, y estén destinados a ese uso.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(64 AS Decimal(5, 0)), N'Alimentos irradiados.', N'Alimentos irradiados.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(65 AS Decimal(5, 0)), N'Alimentos genéticamente modificados.', N'Alimentos genéticamente modificados.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(66 AS Decimal(5, 0)), N'Comercio minorista de alimentación.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos dedicados a la venta al por menor de productos alimenticios destinados al consumo humano, incluidos pan y pasteles en establecimientos sin elaboración, y carne, pescado, y precocinados cuando se trate de productos envasados sin manipulación en el establecimiento y aunque la venta se realice en instalaciones de comercio mayorista, fábricas u otros lugares de producción o sus anejos y otros establecimientos cuya actividad principal sea distinta y los integrados en recintos comerciales colectivos, incluyendo todo tipo de todo tipo de productos al por menor sin manipulación.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(67 AS Decimal(5, 0)), N'Patatas fritas y productos de aperitivo (elaboración y envasado).', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos dedicados a la elaboración y comercialización (en instalaciones fijas o en no permanentes) de patatas fritas y productos de aperitivo, entendiendo por estos últimos aquellos preparados de utilización básicamente fruitiva como aperitivos, obtenidos por secado, tostación, extrusión, fritura, troquelado o procedimientos similares y a partir de  materias primas de origen animal o vegetal (cortezas, snacks, palitos, prettzels, lazos y similares).', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(68 AS Decimal(5, 0)), N'Comedores colectivos: Establecimientos de hostelería grupo 0. ', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de hostelería del grupo 0.
Los establecimientos de hostelería del grupo 0 son establecimientos que no elaboran alimentos, sino que solo sirven bebidas y/o alimentos. Se incluyen los establecimientos que exponen y sirven productos elaborados por industrias autorizadas.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(69 AS Decimal(5, 0)), N'Comedores colectivos: Establecimientos de hostelería grupo I.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de hostelería del grupo I.
Los establecimientos de hostelería del grupo I son aquellos comedores colectivos que elaboran alimentos para su consumo inmediato, pero sin servicio de comidas completas en locales o zonas al efecto. Se incluyen en este grupo, los bares con elaboración de pinchos y/o platos combinados, pizzerías, hamburgueserías, bocaterías, cafeterías y asimilables.
 También se incluyen establecimientos que elaboran menús simples de bajo riesgo en peque¦as cantidades, siendo el aprovisionamiento de materias primas perecederas ajustadas a su consumo diario y manteniendo estas condiciones estables a lo largo de la semana y en cualquier época del a¦o.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(70 AS Decimal(5, 0)), N'Comedores colectivos: Establecimientos de hostelería grupo II.', N'Establecer%20las%20condiciones%20y%20requisitos%20espec%EDficos%20que%20deben%20cumplir%20los%20establecimientos%20de%20hosteler%EDa%20del%20grupo%20II%2C%20de%20acuerdo%20a%20su%20riesgo%20sanitario.%0D%0ALos%20establecimientos%20de%20hosteler%EDa%20del%20grupo%20II%20son%20aquellos%20comedores%20colectivos%20que%20elaboran%20y%20sirven%20men%FAs%20o%20comidas%20completas%2C%20muy%20variadas%2C%20con%20ingredientes%20de%20diversa%20naturaleza%20y%20origen%2C%20que%20sufren%20preparaciones%20tambi%E9n%20variadas%2C%20y%20con%20servicio%20de%20los%20mismos%20en%20un%20comedor%20o%20zona%20habilitada%20al%20efecto.%20Se%20incluyen%20establecimientos%20de%20hosteler%EDa%20con%20men%FA%20y/o%20carta%2C%20y%20asimilables.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'2019-03-12' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(71 AS Decimal(5, 0)), N'Comedores colectivos: Establecimientos de hostelería grupo III.', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de hostelería del grupo III, de acuerdo a su riesgo sanitario.
Los establecimientos de hostelería del grupo III son aquellos comedores colectivos que elaboran productos muy variados en cuanto a preparación, ingredientes, coberturas y nivel de riesgo sanitario, pero en grandes cantidades, con preparación previa en gran parte y a gran número de comensales simultáneamente (capacidad superior a 150 comensales).', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(72 AS Decimal(5, 0)), N'Almacén frigorífico de carnes de mamíferos de caza de granja.', N'Establecer las condiciones y requisitos específicos que deben cumplir los almacenes frigoríficos de carnes y despojos ,embalados o no, procedentes de mamíferos de caza de granja que no se someten a ninguna manipulación salvo aquella necesarias para el almacenamiento de las mismas.
Entendiendo por mamíferos de caza de granja aquellos mamíferos terrestres no considerados domésticos, distintos de los bovinos (incluidas las especies Bubalus bubalis y Bison bison), porcinos, ovinos, caprinos y solípedos domésticos, pero criados como animales domésticos. Sin embargo no se considerarán caza de granja aquellos mamíferos silvestres que vivan en un territorio cerrado en condiciones de libertad semejantes a las de caza silvestre.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(73 AS Decimal(5, 0)), N'Sala de despiece de carnes de mamíferos de caza de granja.', N'Establecer las condiciones y requisitos específicos que deben cumplir las salas de despiece de carne fresca de mamíferos de caza de granja dedicadas a la obtención y comercialización de porciones más peque¦as que las canales, las medias canales y las medias canales despiezadas en un máximo de tres piezas o los cuartos, al deshuese de las mismas, su envasado o no y a la comercialización de despojos (enteros envasados o no) o fileteados. 
Entendiendo por mamíferos de caza de granja aquellos mamíferos terrestres no considerados domésticos, distintos de los bovinos (incluidas las especies Bubalus bubalis y Bison bison), porcinos, ovinos, caprinos y solípedos domésticos, pero criados como animales domésticos. Sin embargo no se considerarán caza de granja aquellos mamíferos silvestres que vivan en un territorio cerrado en condiciones de libertad semejantes a las de caza silvestre.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(74 AS Decimal(5, 0)), N'Establecimientos procesadores de conservas y semiconservas vegetales y zumos.', N'Establecer los requisitos técnico-sanitarios que tienen que cumplir los establecimientos dedicados a la actividad de elaboración y comercialización de conservas y semiconservas vegetales incluidos los zumos de frutas y néctares.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(75 AS Decimal(5, 0)), N'Mataderos de poca capacidad.', N'Mataderos de poca capacidad.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(76 AS Decimal(5, 0)), N'Mataderos de aves de poca capacidad.', N'Mataderos de aves de poca capacidad.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(77 AS Decimal(5, 0)), N'Establecimientos procesadores de aceitunas y encurtidos.', N'Establecer los requisitos técnico-sanitarios que tienen que cumplir los establecimientos dedicados a la actividad de almacenamiento y elaboración de frutas y hortalizas secas, desecadas y deshidratadas; elaboración de aceitunas y encurtidos.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(78 AS Decimal(5, 0)), N'Centros de recogida de leche y centros de normalización.', N'Establecer las condiciones y requisitos específicos que, además de los indicados de forma general, deben cumplir de forma especifica los establecimientos dedicados a la recogida y normalización de leche cruda.
Se entiende por leche cruda la leche de vaca, oveja, cabras o búfalas que no haya sido calentada a una temperatura superior a 40º C ni sometida a un tratamiento de efecto equivalente.
Los Centros de recogida de leche son establecimientos donde se puede recoger la leche cruda procedente de las explotaciones y, en su caso, enfriarse y purificarse. De allí es llevada a los establecimientos de tratamiento térmico o de transformación en productos lácteos. 
Los Centros de normalización son establecimientos no ligados a un centro de recogida ni a un establecimiento de tratamiento o transformación en los que la leche cruda procedente de las explotaciones puede someterse a un desnatado o a una modificación del contenido en componentes normales de la leche.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(79 AS Decimal(5, 0)), N'Envasadores de leche cruda.', N'Establecer las condiciones y requisitos específicos que, además de los indicados de forma general, deben cumplir de forma especifica los establecimientos dedicados a la producción y comercialización de leche cruda.
Son establecimientos anexos a explotaciones de producción en los que se procede al envasado de leche cruda para su comercialización dentro de la CAPV.  Generalmente son establecimientos de poca producción 
Se entiende por establecimientos de producción limitada   aquellos cuya producción anual es inferior a 750.000 litros en leche de vaca, 250.000 litros en leche de oveja, 350.000 litros en leche de cabra, o 700.000 litros en caso de mezcla de varias especies.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(80 AS Decimal(5, 0)), N'Establecimientos de tratamiento térmico de leche para consumo.', N'Establecer las condiciones y requisitos específicos que, además de los indicados de forma general, deben cumplir de forma especifica los establecimientos dedicados a la producción y comercialización de leche de consumo tratada térmicamente. 
 Son establecimientos en los que se trata térmicamente la leche cruda procedente de las explotaciones de producción, de centros de recogida o de centros de normalización. Se entiende por tratamiento térmico cualquier tratamiento por calentamiento que, inmediatamente después de su aplicación, tenga como consecuencia una reacción negativa a la prueba de la fosfatasa.
Se entiende por leche de consumo tratada térmicamente la leche de consumo destinada a la venta al consumidor final y a las colectividades, obtenida mediante tratamiento térmico y que se presente en las formas de leche pasteurizada, leche pasteurizada sometida a alta pasteurización, leche esterilizada y leche UHT.
Se entiende por terminación el calentamiento de la leche cruda durante 15 segundos como mínimo, a una temperatura comprendida entre 57º C y 68º C, de forma que la leche, después de ese tratamiento, reaccione positivamente a la prueba de la fosfatasa.
Se entiende por establecimientos de producción limitada   aquellos cuya producción anual es inferior a 750.000 litros en leche de vaca, 250.000 litros en leche de oveja, 350.000 litros en leche de cabra, o 700.000 litros en caso de mezcla de varias especies.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(82 AS Decimal(5, 0)), N'Elaboración de masas fritas.', N'Elaboración de masas fritas', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(91 AS Decimal(5, 0)), N'Leche', N'Objetivo%20de%20la%20IT%20LECHE', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(92 AS Decimal(5, 0)), N'Instrucción Técnica Número 100', N'Recoge%20condiciones%20generales%20para%20aquellos%20establecimientos%20para%20los%20que%20no%20se%20ha%20desarrollado%20una%20Instrucci%F3n%20T%E9cnica%20espec%EDfica.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(93 AS Decimal(5, 0)), N'Punto Caliente Pan', N'Recoger%20Objetivo', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(95 AS Decimal(5, 0)), N'Preparados alimenticios para regímenes dietéticos y/o especiales.', N'Establecer las condiciones y requisitos que de manera específica deben cumplir los establecimientos dedicados a la actividad de elaboración, envasado y comercialización de los preparados alimenticios dietéticos y/o destinados a una alimentación especial, así como las características específicas que deben cumplir los productos incluidos en este grupo de alimentos, de acuerdo con la definiciones que figuran en el anexo 2.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(97 AS Decimal(5, 0)), N'Carnicerías', N'Establecer las condiciones y requisitos específicos que deben cumplir las carnicerías, entendiendo por éstas como aquellos establecimientos que:
1º.Están formados por un local o conjunto de locales bajo titularidad única, que según su ubicación pueden:
a)Estar independientes
b)Estar integrados en una unidad comercial de mayor entidad, compartiendo servicios-vestuarios y elementos comunes de la unidad con otros establecimientos.
c)Ser una sección de un establecimiento polivalente, debiendo estar claramente separada e identificada del resto de secciones y podrán compartir los servicios-vestuarios y elementos comunes de dicho establecimiento polivalente.
2º.Se dedican a la manipulación, preparación y presentación de carnes y despojos frescos (refrigerados o congelados) con o sin hueso en sus diferentes modalidades: fileteado, troceado, picado, mechado y otras análogas a estas, para suministro directamente al consumidor final bien en venta directa o reparto a domicilio, teniendo en cuenta además lo recogido en el punto nº 6 de este apartado.
3º.Las carnes y despojos que comercializan deben ser aptas para consumo humano, obtenidas en establecimientos autorizados y provenientes de animales domésticos (especies bovina, porcina, ovina, caprina, solípedos, gallinas, pavos, pintadas, patos, ocas y conejos) mamíferos terrestres y aves silvestres reproducidos, criados y sacrificados en cautividad, caza silvestre y reses de lidia de espectáculos taurinos. Según esta definición, y a efectos de clarificar las actividades, puede suceder que en mercados y galerías comerciales existan establecimientos que su actividad principal y casi única sea la de comercializar carnes de aves. En este caso su denominación sería la de POLLERIA, pero a  efectos de requisitos higiénico-sanitarios serian los recogidos en la presente IT. 
4º.No tienen autorización para la elaboración propia de preparados cárnicos (frescos, crudos-adobados), productos cárnicos, otros productos de origen animal y platos cocinados cárnicos, pero sí para la comercialización de éstos si proceden de industrias autorizadas, o estas carnicerías actúan como sucursales de otro establecimiento considerado central.
5º.Entendemos por sucursales a las carnicerías que incorporan a los productos que comercializan, aquellos productos elaborados en otro considerado central, de la misma titularidad que ellos y localizados en la misma Comarca de Salud Pública donde se encuentra este establecimiento central. Asi tenemos según Territorio Histórico:
·En Bizkaia: Interior, Gernika Lea-Artibay, Uribe Kosta, Margen Izquierda-Encartaciones y Bilbao.
·En Guipúzcoa: Urola, Deba, Tolosa-Goierri, Bidasoa y Donosita.
·En Araba: Araba Rural, Aiara y Rioja Alavesa.
6º. Con excepción de los preparados cárnicos frescos y las carnes picadas, estos establecimientos solamente podrán suministrar a los establecimientos de comidas preparadas no sujetos a inscripción en el R.G.S.A. ubicados dentro del ámbito territorial de la Comarca de Salud Pública en la que se encuentra ubicado dicho establecimiento.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(98 AS Decimal(5, 0)), N'Carnicería-Charcutería', N'Establecer las condiciones y requisitos específicos que deben cumplir las carnicerías-charcuterías, entendiendo por éstas como aquellos establecimientos que:
1º.Están formados por un local o conjunto de locales bajo titularidad única, que según su ubicación pueden:
a)Estar independientes
b)Estar integrados en una unidad comercial de mayor entidad, compartiendo servicios-vestuarios y elementos comunes de la unidad con otros establecimientos.
c)Ser una sección de un establecimiento polivalente, debiendo estar claramente separada e identificada del resto de secciones y podrán compartir los servicios-vestuarios y elementos comunes de dicho establecimiento polivalente.
2º.Se dedican a la manipulación, preparación y presentación de carnes y despojos frescos (refrigerados o congelados) con o sin hueso en sus diferentes modalidades: fileteado, troceado, picado, mechado y otras análogas a estas. Además podrán elaborar: 
- preparados de carne (frescos y crudas adobados) 
- productos cárnicos
- otros productos de origen animal
- platos cocinados cárnicos
- productos tradicionales que las autoridades sanitarias autoricen expresamente, una vez valoradas las peticiones que las asociaciones de carniceros presenten.
Las carnes y despojos que comercializan deben ser aptas para consumo humano, obtenidas en establecimientos autorizados y provenientes de animales domésticos (especies bovina, porcina, ovina, caprina, solípedos, gallinas, pavos, pintadas, patos, ocas y conejos) mamíferos terrestres y aves silvestres reproducidos, criados y sacrificados en cautividad, caza silvestre y reses de lidia de espectáculos taurinos.
3º.Los productos que elaboran estos establecimientos solo pueden ser comercializadas en sus propias dependencias de venta al público y en las sucursales.
Entendemos por sucursales a las carnicerías que incorporan a los productos que comercializan, aquellos productos elaborados en otro considerado central, de la misma titularidad que ellos y localizados en la misma Comarca de Salud Pública donde se encuentra este establecimiento central. 
Asi tenemos según Territorio Histórico:
En Bizkaia: Interior, Gernika Lea-Artibay, Uribe Kosta, Margen Izquierda-Encartaciones y Bilbao.
En Guipúzcoa: Urola, Deba, Tolosa-Goierri, Bidasoa y Donostia.
En Araba: Araba Rural, Aiara y Rioja Alavesa.
5º. Con excepción de los preparados cárnicos frescos y las carnes picadas, estos establecimientos solamente podrán suministrar a los establecimientos de comidas preparadas no sujetos a inscripción en el R.G.S.A. ubicados dentro del ámbito territorial de la Comarca de Salud Pública en la que se encuentra ubicado dicho establecimiento.
', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(99 AS Decimal(5, 0)), N'Elaboración de platos preparados no industriales Gurpo II', N'Establecer las condiciones y requisitos específicos que deben cumplir los establecimientos de elaboración de platos preparados no industriales del grupo II, de acuerdo a su riesgo sanitario.
Los establecimientos de elaboración de platos preparados no industriales del grupo II son aquellos cuya actividad sea facilitar comidas preparadas que no se consumen en el mismo local donde se elaboran, pudiendo ser vendidas al consumidor final para su consumo fuera del establecimiento de elaboración, o suministradas al mismo en su domicilio particular.
Son establecimientos que elaboran y venden comidas completas, muy variadas, con ingredientes de diversa naturaleza y origen, que sufren preparaciones también variadas', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(100 AS Decimal(5, 0)), N'Otros productos de origen animal.', N'Establecer las condiciones y requisitos específicos que deben reunir los establecimientos dedicados a la producción/transformación, envasado, almacenamiento y comercialización de, otros productos de origen animal siendo estos: 
%u2022Las grasas animales fundidas: grasas obtenidas por fundición mediante tratamiento térmico de la carne incluyendo los huesos, y destinados a consumo humano.
%u2022Los chicharrones: residuos proteicos de la fundición de grasas, tras la separación parcial de la grasa y el agua.
%u2022Las gelatinas: la proteína natural, soluble, gelificante o no, obtenida mediante hidrólisis parcial del colágeno producido a partir de huesos, pieles, tendones y nervios de animales.
%u2022El colágeno: producto a base de proteína obtenido a partir de los huesos, pieles, tendones y nervios de animales y fabricado según lo establecido en la normativa correspondiente.
%u2022Estómagos, vejigas e intestinos tratados: han sido sometidos a tratamientos como salado, calentamiento o secado después de haberse extraído y limpiarlos.
%u2022También están dentro de este epígrafe: los extractos de carne, harinas de carne, corteza de cerdo en polvo, sangre salada, sangre seca, el plasma sanguíneo salado o seco, todo con destino a consumo humano.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(101 AS Decimal(5, 0)), N'Queserías tradicionales y otras', N'Establecer las condiciones y requisitos específicos que, además de los indicados de forma general, deben cumplir de forma especifica los establecimientos en los que se elaboran quesos  de características tradicionales y otros tipos, elaborados a partir de leche cruda y que pasan un proceso de maduración superior a 60 días antes de su venta y consumo.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(102 AS Decimal(5, 0)), N'Establecimientos de elaboración de productos lácteos.', N'Establecer las condiciones y requisitos específicos que, además de los indicados de forma general, deben cumplir de forma especifica los establecimientos en los que se procede al tratamiento, transformación y envasado de productos lácteos.
Se entiende por producto lácteo los productos a base de leche, teniendo en cuenta que se pueden a¦adir sustancias para su elaboración siempre que no sustituyan total o parcialmente alguno de de los componentes de la leche y teniendo en cuenta que la leche sea el componente esencial.
Se entiende por leche destinada a la elaboración de productos lácteos la leche cruda líquida o congelada, que haya sufrido o no algún tratamiento físico autorizado como por ejemplo un tratamiento térmico o una termización y que su composición haya sido modificada o no adición o sustracción de componentes normales de la leche.
Se entiende por establecimientos de características tradicionales o de producción limitada   aquellos cuya producción anual es inferior a 750.000 litros en leche de vaca, 250.000 litros en leche de oveja, 350.000 litros en leche de cabra, o 700.000 litros en caso de mezcla de varias especies. ', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(103 AS Decimal(5, 0)), N'Elaboración de harina de baja producción', N'Establecer las condiciones y requisitos que de manera general, deben cumplir estos establecimientos alimentarios, dedicados a la molienda de granos de forma no industrial con excasa actividad de producción y ambito local. ', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'2022-03-29' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(105 AS Decimal(5, 0)), N'Establecimiento con autorización sanitaria para tratamiento térmico de leche', N'Establecer las condiciones y requisitos específicos que, además de los indicados de forma general, deben cumplir de forma especifica los establecimientos dedicados a la producción y comercialización de leche de consumo tratada térmicamente. Son establecimientos en los que se trata térmicamente la leche cruda procedente de las explotaciones de producción, de centros de recogida o de centros de normalización. Se entiende por tratamiento térmico cualquier tratamiento por calentamiento que, inmediatamente después de su aplicación, tenga como consecuencia una reacción negativa a la prueba de la fosfatasa. Se entiende por leche de consumo tratada térmicamente la leche de consumo destinada a la venta al consumidor final y a las colectividades, obtenida mediante tratamiento térmico y que se presente en las formas de leche pasteurizada, leche pasteurizada sometida a alta pasteurización, leche esterilizada y leche UHT. Se entiende por terminación el calentamiento de la leche cruda durante 15 segundos como mínimo, a una temperatura comprendida entre 57 grados Centigrados y 68 grados Centigrados, de forma que la leche, después de ese tratamiento, reaccione positivamente a la prueba de la fosfatasa', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(106 AS Decimal(5, 0)), N'Auditoría de sistemas de APPCC/HACCP', N'Establecer las condiciones y requisitos que deben valorarse en una auditoría para evaluar si un establecimiento dispone de un sistema de autocontrol  correctamente planificado, implantado y ejecutado.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
INSERT [SYSPRO].[TSCIJPR1] ([TPR1_COD_TIPO], [TPR1_DES_TIPO], [TPR1_TEX_TIPO], [TPR1_DES_TIPO_E], [TPR1_TEX_TIPO_E], [TPR1_FEC_BAJA]) VALUES (CAST(107 AS Decimal(5, 0)), N'Complementos alimenticios', N'Establecer las condiciones y requisitos que de forma específica deben cumplir los establecimientos dedicados a la actividad de elaboración, envasado y comercialización de complementos alimenticios así como las condiciones y requisitos de los productos que se producen o comercializan en dichos establecimientos.', N'DESCRIPCION_EUSKERA', N'TEXTO_EUSKERA', CAST(N'0001-01-01' AS Date))
GO
ALTER TABLE [SYSPRO].[TSCIJPR1] ADD  CONSTRAINT [DF_TSCIJPR1_TPR1_FEC_BAJA]  DEFAULT ([dbo].[DATE]('01/01/0001')) FOR [TPR1_FEC_BAJA]
GO
