USE [BSCIJCEN_PRO]
GO
/****** Object:  Table [SYSPRO].[TSCIJPR4]    Script Date: 21/04/2026 15:37:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SYSPRO].[TSCIJPR4](
	[TPR4_COD_IT] [decimal](3, 0) NOT NULL,
	[TPR4_DES_IT] [varchar](100) NOT NULL,
	[TPR4_TEX_IT] [varchar](500) NOT NULL,
	[TPR4_DES_IT_E] [varchar](100) NOT NULL,
	[TPR4_TEX_IT_E] [varchar](500) NOT NULL
) ON [PRIMARY]
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(221 AS Decimal(3, 0)), N'PGAH', N'PGAH', N'PGAH', N'PGAH')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(1 AS Decimal(3, 0)), N'Condiciones Generales de Emplazamiento ', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con su emplazamiento.', N'Condiciones Generales de Emplazamiento ', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con su emplazamiento.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(2 AS Decimal(3, 0)), N'Condiciones Generales de vías de acceso ', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con las vías de acceso y zonas utilizadas para el tráfico rodado.', N'Condiciones Generales de vías de acceso ', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con las vías de acceso y zonas utilizadas para el tráfico rodado.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(3 AS Decimal(3, 0)), N'Dise¦o y disposición de edificios y locales', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con las vías de acceso y zonas utilizadas para el tráfico rodado.', N'Dise¦o y disposición de edificios y locales', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con las vías de acceso y zonas utilizadas para el tráfico rodado.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(4 AS Decimal(3, 0)), N'Dimensiones de edificios y locales', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con las dimensiones de edificios y locales.', N'Dimensiones de edificios y locales', N'Establecer las Condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con las dimensiones de edificios y locales.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(5 AS Decimal(3, 0)), N'Estructuras internas de los locales', N'Establecer condiciones y requisitos que deben cumplir de manera general, los establecimientos alimentarios, en relación con las estructuras internas de los locales.', N'Estructuras internas de los locales', N'Establecer condiciones y requisitos que deben cumplir de manera general, los establecimientos alimentarios, en relación con las estructuras internas de los locales.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(6 AS Decimal(3, 0)), N'Abastecimiento de agua', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con el abastecimiento de agua.', N'Abastecimiento de agua', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con el abastecimiento de agua.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(7 AS Decimal(3, 0)), N'Efluentes y aguas residuales', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con los efluentes y aguas residuales en el conjunto de establecimientos alimentarios.', N'Efluentes y aguas residuales', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con los efluentes y aguas residuales en el conjunto de establecimientos alimentarios.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(8 AS Decimal(3, 0)), N'Iluminación', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la iluminación.', N'Iluminación', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la iluminación.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(9 AS Decimal(3, 0)), N'Ventilación', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la ventilación.', N'Ventilación', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la ventilación.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(10 AS Decimal(3, 0)), N'Equipos y utensilios', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con los equipos y utensilios.', N'Equipos y utensilios', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con los equipos y utensilios.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(11 AS Decimal(3, 0)), N'Vestuarios y Servicios de Higiene y Aseo', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con el vestuario, servicios de higiene y aseo.!!!!', N'Vestuarios y Servicios de Higiene y Aseo', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con el vestuario, servicios de higiene y aseo.!!!!')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(12 AS Decimal(3, 0)), N'Higiene personal', N'Establecer las condiciones y requisitos que de manera general, debe cumplir el personal relacionado con los alimentos, establecimientos e industrias de alimentación; y que afectan tanto al personal que realiza tareas de manipulación, como al personal que ????', N'Higiene personal', N'Establecer las condiciones y requisitos que de manera general, debe cumplir el personal relacionado con los alimentos, establecimientos e industrias de alimentación; y que afectan tanto al personal que realiza tareas de manipulación, como al personal que ????')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(13 AS Decimal(3, 0)), N'Limpieza y desinfección', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la limpieza y desinfección.', N'Limpieza y desinfección', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la limpieza y desinfección.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(14 AS Decimal(3, 0)), N'Control de plagas', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios en relación con el control de plagas. ', N'Control de plagas', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios en relación con el control de plagas. ')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(15 AS Decimal(3, 0)), N'Almacenamiento, manejo y eliminacion de desechos, subproductos y devoluciones', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, referidos a las condiciones de manejo de desechos, subproductos y devoluciones.', N'Almacenamiento, manejo y eliminacion de desechos, subproductos y devoluciones', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, referidos a las condiciones de manejo de desechos, subproductos y devoluciones.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(16 AS Decimal(3, 0)), N'Medios de transporte', N'Establecer las condiciones y requisitos que de manera general, deben cumplir  los establecimientos alimentarios, en relación con los vehículos utilizados por dichos establecimientos para el transporte de productos objeto de su actividad. ', N'Medios de transporte', N'Establecer las condiciones y requisitos que de manera general, deben cumplir  los establecimientos alimentarios, en relación con los vehículos utilizados por dichos establecimientos para el transporte de productos objeto de su actividad. ')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(17 AS Decimal(3, 0)), N'Higiene de las Operaciones', N'Establecer las condiciones y requisitos, que de manera general deben cumplirse en los establecimientos alimentarios, en lo referido a las condiciones de higiene en las que deben desarrollarse las operaciones o procesos a los que son sometidos los alimento????', N'Higiene de las Operaciones', N'Establecer las condiciones y requisitos, que de manera general deben cumplirse en los establecimientos alimentarios, en lo referido a las condiciones de higiene en las que deben desarrollarse las operaciones o procesos a los que son sometidos los alimento????')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(18 AS Decimal(3, 0)), N'Formación de manipuladores', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la formación continuada de sus manipuladores. ', N'Formación de manipuladores', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, en relación con la formación continuada de sus manipuladores. ')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(19 AS Decimal(3, 0)), N'Envasado Embalado', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, para la envoltura, envasado y embalado los productos que elaboren o comercialicen.', N'Envasado Embalado', N'Establecer las condiciones y requisitos que de manera general, deben cumplir los establecimientos alimentarios, para la envoltura, envasado y embalado los productos que elaboren o comercialicen.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(20 AS Decimal(3, 0)), N'Etiquetado y Trazabilidad', N'Establecer las condiciones y requisitos que deben cumplir los productos alimenticios según la norma General de Etiquetado y su trazabilidad en la cadena de producción alimentaria desde el productor hasta el consumidor.', N'Etiquetado y Trazabilidad', N'Establecer las condiciones y requisitos que deben cumplir los productos alimenticios según la norma General de Etiquetado y su trazabilidad en la cadena de producción alimentaria desde el productor hasta el consumidor.')
GO
INSERT [SYSPRO].[TSCIJPR4] ([TPR4_COD_IT], [TPR4_DES_IT], [TPR4_TEX_IT], [TPR4_DES_IT_E], [TPR4_TEX_IT_E]) VALUES (CAST(21 AS Decimal(3, 0)), N'IT Genérica que engloba todas las anteriores.', N'IT Genérica que engloba todas las anteriores.', N'IT Genérica que engloba todas las anteriores.', N'IT Genérica que engloba todas las anteriores.')
GO
